### ISSUE TITLE
Upgrade aws-rds broker DB versions

### ISSUE THREAD

**Issue by mxplusb** [cloud-gov/cg-product#1187] opened 2020-01-09 19:22 UTC
In order to deploy supported PostgreSQL versions, the aws-rds broker needs to deploy supported versions.

This is the notification we received from a customer

> The shared PostgreSQL version used is 9.4.7 (as per document) whose EOL is Feb 13, 2020. Anyone who will create a service with shared-psql will create an PSQL instance with version 9.4.

It aligns with the PostgreSQL version support: https://www.postgresql.org/support/versioning/

### Prep:

- [x] migrate to recreatable prarameter group in dev
- [x] migrate to recreatable prarameter group in staging
- [x] migrate to recreatable prarameter group in prod

### Shared DBs:

- [x] upgrade shared RDS in dev
- [x] upgrade shared RDS in staging

### Internal DBs:

- [x] upgrade internal RDS in dev
- [x] upgrade internal RDS in staging

### During the maintenance window at 10:30 am PT on March 10th:

- [x] plan upgrades for shared and internal DBs in prod
- [x] snapshot shared and internal RDS in prod
- [x] upgrade shared and internal RDS in prod
- [x] update cg-site documentation on versions.  PR in https://github.com/cloud-gov/cg-site/pull/1559

## Security considerations

Will eventually pull in all updates and CVEs from major upgrades.

**Comment by karareinsel** [comment] 2020-01-13 17:24
Have until 2/14/2020 until this increases in urgency (sprint 20.2.7).

**Comment by tammersaleh** [comment] 2020-01-28 18:51
OK, so I didn't read the original message closely enough, and assumed that this applied to _all_ postgres RDS instances created by the aws-rds broker. Instead, this is _only_ for the `shared-psql` plan, which provisions databases inside the single shared RDS instance.

So the good news is that new dedicated psql instances are created with whatever the latest AWS version is. 

The bad news is that is looks like our shared RDS instance is likely going to be [automatically upgraded out from under us at any moment](https://forums.aws.amazon.com/ann.jspa?annID=6993):

> As part of the retirement plan for Amazon RDS PostgreSQL 9.4, starting September 15, 2019, we will be disabling creation of any new PostgreSQL 9.4 instances using the AWS console. Starting November 15, 2019, we will be performing forced auto minor version upgrades on your remaining 9.4 instances to the recent minor version of 9.4. You can continue to do PostgreSQL 9.4 restores and read replica creations until January 15, 2020. **_Starting January 15, 2020, your remaining 9.4 instances will be force upgraded to the most recent minor version of PostgreSQL 11._** If we are not able to upgrade to PostgreSQL 11 for any reason, we will upgrade to the 9.5 version. After that upgrade process is complete, any instance restored from a snapshot of PostgreSQL 9.4 version will automatically and immediately be upgraded to a currently supported version.

**Comment by eddietejeda** [comment] 2020-01-28 19:33
Why would someone choose `shared-psql`, especially since it does not impact their cost? 

How many folks do we have there? Would it be easier to get people to move away from this?

**Comment by bengerman13** [comment] 2020-01-28 19:48
are the non-shared instances available in sandboxes?

**Comment by tammersaleh** [comment] 2020-01-28 21:22
I can confirm that we are allowing the creation of non-shared databases in the sandbox spaces.  If you think it's fine to tell users to move to dedicated instances (and shut down the creation of new shared ones), then that's probably easier.

**Comment by bengerman13** [comment] 2020-01-28 21:34
@eddietejeda it might make sense to move folks off this, but it wouldn't get us out of this upgrade.
If we decide to drop this, we'd need to follow our [deprecation procedure](https://cloud.gov/docs/technology/responsibilities/#deprecation-policy), which takes 180 days (at a minimum) so we'd need to do this upgrade anyway.

**Comment by eddietejeda** [comment] 2020-01-28 23:21
If not needed, let's get deprecate.

**Comment by eddietejeda** [comment] 2020-01-29 00:39
Consideration: If sandboxes are using their own DB, would the DB be deleted once sandbox trial period is over?

**Comment by tammersaleh** [comment] 2020-01-29 17:07
@bengerman13 is mostly correct:  we definitely need to put this fire out before we can do anything else, and removing the shared plans will take 180 days.

However, the plan of action is to upgrade everything to Postgres 9.5, which doesn't EOL for another year.  That's the smallest change we're forced to make, and should disrupt our current users the least.  

But we still need to get to an actually current version of PgSQL (11), which means we'll have to run _two_ shared RDS instances (one at 11, and one at 9.5). We'll need to modify the plans and possibly broker code to work between them.  At that point, I'd rather just kill the shared plan altogether. 

So I suggest we continue upgrading the shared plans to 9.5, _and_ start the shared-psql (and shared-mysql?) deprecation process at the same time.

**Comment by mxplusb** [comment] 2020-01-30 23:46
> if sandboxes are using their own DB, would the DB be deleted once sandbox trial period is over?

@eddietejeda yes they will, when you delete a space in CF, you can opt into force deleting their child resources (aka databases).

**Comment by tammersaleh** [comment] 2020-02-03 19:30
This is merged as part of https://github.com/18F/aws-broker/pull/55, and has gone through the pipeline to prod.

**Comment by soutenniza** [comment] 2020-02-18 20:43
Customer during office hours pointed out Postgres was showing version 9.4.20. Confirmed with https://github.com/18F/aws-broker/blob/fb644c38f51104fe0b1b72d7e3e0c896fec39922/ci/pipeline.yml#L442-L491

**Comment by tammersaleh** [comment] 2020-02-20 19:08
Confirmed that shared in dev is at 9.5.15.

**Comment by tammersaleh** [comment] 2020-02-20 23:23
I've hit a known issue in upgrading RDS via terraform going back to 2017, and continuing to as recently as Jan 8, 2020:

* https://github.com/terraform-providers/terraform-provider-aws/issues/6448
* https://github.com/terraform-providers/terraform-provider-aws/issues/2402
* https://github.com/terraform-providers/terraform-provider-aws/issues/1571
* https://github.com/terraform-providers/terraform-provider-aws/issues/526

**Comment by tammersaleh** [comment] 2020-03-04 18:06
The maintenance window has been moved to Tuesday, March 10th, due to an incident that was in play on Tuesday, March 3rd.

**Closed** 2020-03-10 20:05 UTC
Labels: operations
